<?php

use Gerencianet\Magento2\Block\Checkout\Success;

/** @var Success $block */
$order = $block->getOrder();
$qrcodepix = $order->getGerencianetQrcodePix();
$boleto = $order->getGerencianetUrlBoleto();
$linha_digitavel = $order->getGerencianetCodigoDeBarras();
$chavepix = $order->getGerencianetChavePix();
$payment = $order->getPayment();
?>
<?php if ($payment->getMethod() === 'gerencianet_pix') : ?>
  <div class="actions-toolbar flex">
    <div class="primary">
      <img src="<?= $qrcodepix ?>" />
    </div>
    <div class="linhes">
      <h3>Linha digitável:</h3>
      <textarea readonly rows="5" name="pixer" id="select-this"><?= $chavepix ?></textarea>
      <div class="actions-toolbar">
        <div class="primary">
          <button id='clickMe'>Copiar</button>
        </div>
      </div>
    </div>
  </div>
<?php endif ?>
<?php if ($payment->getMethod() === 'gerencianet_boleto') : ?>
  <div class="actions-toolbar flex">
    <div class="linhes">
      <h3>Linha digitável:</h3>
      <div class="flex">
          <textarea readonly rows="1" name="pixer" id="select-this"><?= $linha_digitavel ?></textarea>
          <div class="actions-toolbar linha-digitavel">
            <div class="primary">
              <button id='clickMe'>Copiar</button>
            </div>
          </div>
      </div>
    </div>
  </div>
  <div class="view-boleto">
      <iframe src="<?= $boleto ?>" width="100%" height="500px">
      </iframe>
  </div>
  <div class="primary">
      <a target="_blank" class="action primary continue" href="<?php echo $boleto; ?>"><span>Vizualizar Boleto</span></a>
  </div>
<?php endif ?>