<?php
$paymentInfo = $block->getPaymentInfo();
if ($block->getPaymentMethod() === 'gerencianet_boleto') : ?>

  <button type="button" class="action primary btn-gerencianet-pix" data-trigger="trigger">
    <span data-bind="i18n: '<?= $paymentInfo['texto'] ?>'"></span>
  </button>
  <div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'modalClass': 'modalpix',
            'title': 'Boleto',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
        }}">
    <div class="content">
      <input class="action primary btn-gerencianet-boleto" type="button" id="gerencianet" onclick="window.open('<?php echo $paymentInfo['url'] ?>');" value="Baixe seu boleto aqui" />
    </div>
    <h3>Linha digitável:</h3>
    <textarea readonly rows="1" name="pixer" id="select-this"><?= $paymentInfo['linha-digitavel'] ?></textarea>
    <div class="actions-toolbar">
      <div class="primary">
        <button id='clickMe'>Copiar</button>
      </div>
    </div>
  </div>

<?php
elseif ($block->getPaymentMethod() === 'gerencianet_pix') : ?>
  <button type="button" class="action primary btn-gerencianet-pix" data-trigger="trigger">
    <span data-bind="i18n: '<?= $paymentInfo['texto'] ?>'"></span>
  </button>
  <div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'modalClass': 'modalpix',
            'title': 'Escaneie o QRcode',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
        }}">
    <div class="content">
      <img src="<?php echo $paymentInfo['url'] ?>" alt="Erro ao carregar seu QRCode">
    </div>
    <h3>Linha digitável:</h3>
    <textarea readonly rows="5" name="pixer" id="select-this"><?= $paymentInfo['chavepix'] ?></textarea>
    <div class="actions-toolbar">
      <div class="primary">
        <button id='clickMe'>Copiar</button>
      </div>
    </div>
  </div>
<?php endif; ?>